apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-flask
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx  # Matches the NGINX Ingress class
  tls:
    - hosts:
        - test.inhusk.ai
      secretName: flask-tls
  rules:
    - host: test.inhusk.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-flask
                port:
                  number: 80