apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-webserver
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: log-pusher-sidecar
    image: alpine:latest
    command: ["sh", "-c", "while true; do echo 'Pushing logs...'; sleep 10; done"]