apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-test-pod
  namespace: inhusk
spec:
  containers:
  - name: rabbitmq-test
    image: python:3.9-alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      apk add --no-cache py3-pip &&
      pip install pika &&
      python -c "
      import pika
      import sys
      try:
          credentials = pika.PlainCredentials('$RABBITMQ_USER', '$RABBITMQ_PASSWORD')
          parameters = pika.ConnectionParameters(host='$RABBITMQ_HOST', port=$RABBITMQ_PORT, virtual_host='$RABBITMQ_VHOST', credentials=credentials)
          connection = pika.BlockingConnection(parameters)
          connection.close()
          print('Successfully connected to RabbitMQ')
          sys.exit(0)
      except Exception as e:
          print('Failed to connect to RabbitMQ:', str(e))
          sys.exit(1)
      "
    env:
    - name: RABBITMQ_HOST
      value: "rabbitmq-inhusk-rabbitmq"
    - name: RABBITMQ_PORT
      value: "5672"
    - name: RABBITMQ_VHOST
      value: "inhusk-prod"
    - name: RABBITMQ_USER
      value: "inhusk-prod"
    - name: RABBITMQ_PASSWORD
      value: "rabbit1234"
    - name: RABBITMQ_CONNECTION_URL
      value: "amqp://inhusk-prod:rabbit1234@rabbitmq-inhusk-rabbitmq:5672/inhusk-prod"
  restartPolicy: Never
