repoServer:
  extraContainers:
    - name: avp
      command: ["/var/run/argocd/argocd-cmp-server"]
      image: registry.access.redhat.com/ubi8
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      volumeMounts:
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /tmp
          name: tmp
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          subPath: avp.yaml
          name: cmp-plugin
        - mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
          name: custom-tools
  initContainers:
    - name: download-tools
      image: registry.access.redhat.com/ubi8
      env:
        - name: AVP_VERSION
          value: "1.18.0"  # Latest as of Sep 2025
      command: ["sh", "-c"]
      args:
        - >
          curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v/argocd-vault-plugin__linux_amd64 -o argocd-vault-plugin &&
          chmod +x argocd-vault-plugin &&
          mv argocd-vault-plugin /custom-tools/
      volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
  volumes:
    - configMap:
        name: cmp-plugin
      name: cmp-plugin
    - name: custom-tools
      emptyDir: {}
  automountServiceAccountToken: true
