apiVersion: v2
name: my-flask-chart
description: A Helm chart for deploying a Flask API
type: application
version: 0.1.0
appVersion: "1.0"
icon: https://flask.palletsprojects.com/en/2.3.x/_static/flask-icon.png